# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test

.build_base:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CONTAINER_TAG}"
  only:
    - tags

build_arm64:
  extends: .build_base
  stage: build
  variables:
    CONTAINER_TAG: arm64-${CI_COMMIT_TAG}
  tags:
    - arch:arm64
    - size:large

build_amd64:
  extends: .build_base
  stage: build
  variables:
    CONTAINER_TAG: amd64-${CI_COMMIT_TAG}
  tags:
    - arch:amd64
    - size:large
  
